<?php

namespace App\Enums;

enum ErrorCode: string
{
    case UNAUTHENTICATED = 'UNAUTHENTICATED';
    case USER_NOT_FOUND = 'USER_NOT_FOUND';
    case EMAIL_NOT_VERIFIED = 'EMAIL_NOT_VERIFIED';
    case EMAIL_ALREADY_VERIFIED = 'EMAIL_ALREADY_VERIFIED';
    case VALIDATION_FAILED = 'VALIDATION_FAILED';
    case INVALID_CREDENTIALS = 'INVALID_CREDENTIALS';
    case INVALID_VALIDATION_LINK = 'INVALID_VALIDATION_LINK';
    case PASSWORD_MISMATCH = 'PASSWORD_MISMATCH';
    case RATE_LIMIT_EXCEEDED = 'RATE_LIMIT_EXCEEDED';
    case ACTION_NOT_ALLOWED = 'ACTION_NOT_ALLOWED';
}


