<?php

namespace App\Enums;

enum ErrorCode: string
{
    case UNAUTHENTICATED = 'UNAUTHENTICATED';
    case UNAUTHORIZED = 'UNAUTHORIZED';
    case USER_NOT_FOUND = 'USER_NOT_FOUND';
    case EMAIL_NOT_VERIFIED = 'EMAIL_NOT_VERIFIED';
    case EMAIL_ALREADY_VERIFIED = 'EMAIL_ALREADY_VERIFIED';
    case VALIDATION_FAILED = 'VALIDATION_FAILED';
    case INVALID_CREDENTIALS = 'INVALID_CREDENTIALS';
    case INVALID_VALIDATION_LINK = 'INVALID_VALIDATION_LINK';
    case PASSWORD_MISMATCH = 'PASSWORD_MISMATCH';
    case RATE_LIMIT_EXCEEDED = 'RATE_LIMIT_EXCEEDED';
    case ACTION_NOT_ALLOWED = 'ACTION_NOT_ALLOWED';
    case ENUM_NOT_FOUND = 'ENUM_NOT_FOUND';
    case NEED_TO_BE_ADMIN = 'NEED_TO_BE_ADMIN';
    case ACCOUNT_DISABLED = 'ACCOUNT_DISABLED';
    case RESET_PASSWORD_FAILED = 'RESET_PASSWORD_FAILED';

    
    // Global Errors
    case NOT_FOUND = 'NOT_FOUND';
    case SERVER_ERROR = 'SERVER_ERROR';
    case FORBIDDEN = 'FORBIDDEN';
    case METHOD_NOT_ALLOWED = 'METHOD_NOT_ALLOWED';
}


